{
 "title": "03  - Tasks",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"streams\"}, cluster_id)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_streams_info{cluster_id=~\"${cluster}\", application_id=~\".+\"}, application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_streams_info{cluster_type=\"streams\", cluster_id=~\"${cluster}\", application_id=~\"$application\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_streams_stream_thread_metrics_task_created_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "task",
    "label": "task",
    "query": {
     "query": "label_values(kafka_streams_stream_task_metrics_process_rate{cluster_id=~\"$cluster\", instance=~\"${instance}\",thread_id=~\"${thread}\"}, task_id)"
    }
   },
   {
    "name": "partition",
    "label": "partition",
    "query": {
     "query": "label_values(kafka_streams_stream_task_metrics_process_rate{instance=~\"${instance}\",thread_id=~\"${thread}\"}, task_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(thread_id, instance) (kafka_streams_stream_task_metrics_process_latency_avg{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"} > 0)/1000000",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "process latency (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without(task_id, thread_id, instance, cluster_id, job, cluster_type) (kafka_streams_stream_task_metrics_process_latency_avg{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"} > 0)/1000000",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(thread_id, instance) (kafka_streams_stream_task_metrics_process_rate{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without(task_id, thread_id, instance, cluster_id, job, cluster_type) (kafka_streams_stream_task_metrics_process_rate{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "process total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(thread_id, instance)  (kafka_streams_stream_task_metrics_process_total{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "process total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(task_id, thread_id, instance, cluster_id, cluster_type, job) (kafka_streams_stream_task_metrics_process_total{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "record lateness (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(task, thread_id, instance)  (kafka_streams_stream_task_metrics_record_lateness_avg{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"} > 0)",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "record lateness (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without(task_id, thread_id, instance, cluster_id, job) (kafka_streams_stream_task_metrics_record_lateness_avg{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"} > 0)",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "records dropped total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(task, thread_id, instance)  (kafka_streams_stream_task_metrics_dropped_records_total{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "records dropped total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(task_id, thread_id, instance, cluster_id, job, cluster_type) (kafka_streams_stream_task_metrics_dropped_records_total{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  }
 ]
}